name: Build PDFium WASM

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  actions: write

jobs:
  wasm:
    name: PDFium WASM
    uses: bblanchon/pdfium-binaries/.github/workflows/build.yml@master
    with:
      branch: main
      target_os: emscripten
      target_cpu: wasm
      enable_v8: false
      is_debug: false
      build_type: shared
